http:
  routers:
    homebox:
      rule: 'Host(`homebox.{{ env "DOMAIN" }}`)'
      entryPoints:
        - "websecure"
      tls:
        certResolver: "dnsimple"
      service: "homebox"
  services:
    homebox:
      loadBalancer:
        servers:
          - url: 'http://homebox:7745'